### ISSUE TITLE
future indexeddb support?

### ISSUE THREAD

**Issue by c-nv-s** [reusee/domui#2]
do you have any plans to support or add [indexeddb](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) functionality?

**Comment by reusee** [comment]
@c-nv-s Web apis are already supported by the syscall/js package. 
```go
req := js.Global().Get("indexedDB").Call("open", "foo")
req.Set("onsuccess", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
    // ...
}))
```
Or 3rd-party packages: https://pkg.go.dev/search?q=indexeddb
