### ISSUE TITLE
Static Site Generator

### ISSUE THREAD

**Issue by PauloMelo** [reusee/domui#3]
Hi, 
is it possible to use this to create a static site?
using domui as a development tool, is very interesting. The ability to generate a static site on the fly could be very interesting on sites that don’t change so often.

**Comment by reusee** [comment]
I'm not familiar with what should be done to generate a static site. This library is for implementing MVVM pages that contain interactive UI elements.
I think you can use this library to implement an HTML editor that exports pages to a static site.

**Comment by PauloMelo** [comment]
Well if we could capture what is sent to the dom and write those tags down to a file we have the content of the static site, of course we need to pass through all the routes to get each file. 
There should be a way to parse the Specs and instead of creating the nodes in the DOM, writing the tags. What are your thoughts?

**Comment by reusee** [comment]
This sounds like server-side rendering. I can factor out dom-related operations to an interface to allow different rendering backend other than dom implementation in browsers.

**Comment by PauloMelo** [comment]
That sounds very interesting, If i can help just say.
